# PyTorch - 60 Minute Blitz Notes

https://docs.pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

What is PyTorch 

- A replacement for NumPy for the user of GPUs 
- An automatic differentiation library that is great for NNs

In the tutorial we'll cover: 

- Tensors
- torch.autograd
- NNs
- Train a classifier

## Tensors

Tensors are basically array types in PyTorch that have been optimized to run on GPU hardware.

In [ ]:
import torch
import numpy as np

In [ ]:
# Intialization

data = [[1, 2], [3, 4]]  # from data
x_data = torch.tensor(data)

In [ ]:
# from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
# From another tensor
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1315, 0.9942],
        [0.9293, 0.8506]])


In [ ]:
# With random or constant values in configurable shapes
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)


tensor([[0.7512, 0.2167, 0.9546],
        [0.7226, 0.1575, 0.8960]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor attributes
- shape
- datatype
- device on which they are stored


In [10]:
tensor = torch.rand(3, 4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


There are over 100 different [tensor operations](https://docs.pytorch.org/docs/stable/torch.html) and each of them can be run on GPU or CPU which is the key unlock for these large libararies.

In [14]:
tensor

tensor([[0.3364, 0.3844, 0.3329, 0.8058],
        [0.3854, 0.0385, 0.5593, 0.5309],
        [0.8046, 0.8110, 0.6058, 0.5232]])

In [15]:
torch.chunk(tensor, 3)

(tensor([[0.3364, 0.3844, 0.3329, 0.8058]]),
 tensor([[0.3854, 0.0385, 0.5593, 0.5309]]),
 tensor([[0.8046, 0.8110, 0.6058, 0.5232]]))

In [23]:
torch.transpose(tensor, 1, 0)

tensor([[0.3364, 0.3854, 0.8046],
        [0.3844, 0.0385, 0.8110],
        [0.3329, 0.5593, 0.6058],
        [0.8058, 0.5309, 0.5232]])

In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is stored on: {tensor.device}")


In [ ]:
# Indexing and slicing is similar to numpy
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# Joining tensors you can use .cat or .stack
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
# Multiplying tensors

# t1.mul(t2) and t1 * t2 give the elementwise multiplication
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor * tensor}")

# t1.matmul(t1.T) and t1 @ t1.T gives the matrix  product  t1 t1^T
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T) \n {tensor.matmul(tensor.T)} \n")

tensor.matmul(tensor)


tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])

In [44]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t1.shape)
t2 = torch.tensor([[1, 1], [1, 0], [1, 1]])
print(t2.shape)


torch.Size([2, 3])
torch.Size([3, 2])


Any time we see a _ suffix that means the operation is in place. 

In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Tensors on CPU can share their memory location with numpy arrays

In [49]:
t = torch.ones(5)
print(t)

n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
# Numpy --> Tensor
n = np.ones(5)
t = torch.from_numpy(n)
np.add(1, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


### Intro to _torch.autograd_

_torch.autograd_ is PyTorch's automatic differentiation engine. 

NNs are just big nested functions $y = f_p(\ldots f_2(f_1(x))))$ where each funciton $f_i(\cdot)$ are parameterized by weights and biases we store in tensors. 

Training NNs requires

- Forward Propogation: computation of $\hat{y}$ for the given parameter set
- Backward Propogation: the process to adjust the paramters to make $\hat{e} = \hat{y} - y$ smaller


The foward pass is pretty straightforward. Backpropogation is more complex - it does this by traversing the computational graph backwards collecting the derivatives evaluated at the residual error for SGG updates. [See here for the math](https://www.youtube.com/watch?v=tIeHLnjs5U8).

For this tutorial, we're just going to show how it is used - not the math behind it.

In [ ]:
import torch
from torchvision.models import resnet18, ResNet18_Weights

model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/benjamindraves/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100.0%


In [ ]:
# forward pass
prediction = model(data)
prediction.shape

torch.Size([1, 1000])

In [57]:
# compute loss
loss = (prediction - labels).sum()
loss

tensor(-499.8625, grad_fn=<SumBackward0>)

In [ ]:
# backwards pass
loss.backward()

Notice how we called _backward()_ on the error tensor. Autograd then calculates and stores the gradients for each parameter in the .grad attribute.

To actually perform the SGD step, we need an optimizer to know what to do with all of those derivatives.

In [62]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

Finally we call _.step()_ for initiate gradient descnet. The optimizer is the one adjusting each parameter and by its gradient stored in .grad.

In [63]:
optim.step()

So at a very high level we have

- _optim.zero\_grad()_  clear the gradeints from the previous loop
- _pred = model(data)_  foward pass 
- _loss = loss_fn(pred, true)_  compute loss
- _loss.backward()_  compute gradients for each parameter given loss
- _optim.step()_ use the optimizer to update parameters given gradients


There is a ton more to really understand for how back propogation works but lets leave this here for now.

### Differentiation in Autograd

How does autograd actually collect gradients? It finds all parameters with _requires_grad=True_ and that signals to autograd every operation on them should be tracked.

In [ ]:
import torch

a = torch.tensor([2.0, 3.0], requires_grad=True)
b = torch.tensor([6.0, 4.0], requires_grad=True)


In [ ]:
# comput a polynomial form of these tensors
Q = 3 * a**3 - b**2

if we treat (a,b) as parameters of a NN, and Q as the error we can take gradients of Q wrt to (a, b)

$\frac{\partial Q}{\partial a} = 9a^2$

$\frac{\partial Q}{\partial b} = -2b$





When we call _.backward()_ on _Q_ then autograd makes this computation and stores them in the .grad field for the respective tensors attributes a.grad and b.grad

In [ ]:
external = torch.tensor([1.0, 1.0])
Q.backward(gradient=external)

In [ ]:
print(f"Autograd: {a.grad}, Human: {9 * a**2}")
print(f"Autograd: {b.grad}, Human: {-2 * b}")

Autograd: tensor([36., 81.]), Human: tensor([36., 81.], grad_fn=<MulBackward0>)
Autograd: tensor([-12.,  -8.]), Human: tensor([-12.,  -8.], grad_fn=<MulBackward0>)


### Start at the Optional - Reading Vector Calculus using autograd.